image:
  file: .gitpod.Dockerfile

tasks:
  - init: pnpm install
    command: |
      export CLIENT_URL="$(gp url 35729)/livereload.js?snipver=1&port=443"
      { gp await-port 5000 && sleep 5 && gp preview $(gp url 5000) & } &> /dev/null
      gp open src/App.svelte
      pnpm dev
ports:
  - port: 5000
    onOpen: ignore
  - port: 35729
    onOpen: ignore
vscode:
  extensions:
    - svelte.svelte-vscode
    - ardenivanov.svelte-intellisense
    - antfu.browse-lite
    - antfu.iconify
    - antfu.unocss
    - antfu.vite
    - antfu.where-am-i
    - lokalise.i18n-ally
    - dbaeumer.vscode-eslint
    - tabnine.tabnine-vscode
    - esbenp.prettier-vscode
    - usernamehw.errorlens
    - mskelton.one-dark-theme